# Generated by Django 3.1.12 on 2025-04-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
